FROM cblmariner.azurecr.io/base/core:1.0
RUN tdnf install -y \
    build-essential \
    cmake \
    curl-devel \
    gcc \
    git \
    gmock \
    gmock-devel \
    gtest \
    gtest-devel \
    lttng-tools \
    lttng-ust-devel \
    ninja-build \
    openssl-devel \
    rapidjson \
    rpm-build \
    tracelogging-devel \
    util-linux-devel
